Repository Team-GulBi/Frontend, pull requests merged in 2024-12, with the labels that each got.

#22 [design] 검색창 페이지 퍼블리싱
  src/App.tsx
  src/assets/images/bag.png
  src/components/Search/SearchCard/index.tsx
  src/components/common/Header/index.tsx
  src/components/common/ProductCard/index.tsx
  src/components/common/ProductStatusChip/index.tsx
  src/components/common/ProfileStatusChip/index.tsx
  src/pages/Search/page.tsx
Labels: DESIGN, FEAT

#24 deploy: 배포 파일 추가
  build.sh
  vercel.json
Labels: DEPLOY

#26 [feat] api 연동 기초 세팅
  package.json
  src/App.tsx
  src/apis/client.ts
  src/apis/index.ts
  src/hooks/mutations/index.ts
  src/hooks/queries/index.ts
  src/libraries/reactQuery/ReactQuerySetting.tsx
  src/libraries/reactQuery/queryKeys.ts
  src/libraries/stores/index.ts
  src/routes/routePath.ts
  src/routes/router.tsx
  yarn.lock
Labels: FEAT

#29 [feat] 카테고리 조회 api 연동
  src/apis/client.ts
  src/apis/useGetBCategories.ts
  src/apis/useGetMCategories.ts
  src/components/Product/ProductCategory/index.tsx
  src/vite-env.d.ts
Labels: FEAT

#30 [feat] 회원가입 api 연동
  src/apis/signup.ts
  src/hooks/utils/useSignupValidation.ts
  src/pages/Auth/Signup/page.tsx
  src/pages/Onboarding/page.tsx
Labels: FEAT
